[workspace]

members = [
    "modules",
    "relayer",
    "relayer-cli",
    "telemetry",
    "proto",
]

exclude = [
    "proto-compiler"
]

[patch.crates-io]
tendermint              = { path = "../tendermint-rs/tendermint" }   # { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
tendermint-rpc          = { path = "../tendermint-rs/rpc" }          # { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
tendermint-proto        = { path = "../tendermint-rs/proto" }        # { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
tendermint-light-client = { path = "../tendermint-rs/light-client" } # { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
tendermint-testgen      = { path = "../tendermint-rs/testgen" }      # { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
