[workspace]

members = [
    "modules",
    "relayer",
    "relayer-cli",
    "telemetry",
    "proto",
]

exclude = [
    "proto-compiler"
]

[patch.crates-io]
tendermint              = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/929-931" }
tendermint-rpc          = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/929-931" }
tendermint-proto        = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/929-931" }
tendermint-light-client = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/929-931" }
tendermint-testgen      = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/929-931" }
