[workspace]

resolver = "2"

members = [
    "modules",
    "relayer",
    "relayer-cli",
    "relayer-rest",
    "telemetry",
    "proto",
    "tools/integration-test",
    "tools/test-framework",
]

exclude = [
    "ci/no-std-check",
    "proto-compiler"
]

[patch.crates-io]
# patched to a commit on the `eth-bridge-integration` branch of our fork
tendermint              = {git = "https://github.com/heliaxdev/tendermint-rs", rev = "ba13c76b035e63ffec5bacd1f35541e02af5be3f"}
tendermint-rpc          = {git = "https://github.com/heliaxdev/tendermint-rs", rev = "ba13c76b035e63ffec5bacd1f35541e02af5be3f"}
tendermint-proto        = {git = "https://github.com/heliaxdev/tendermint-rs", rev = "ba13c76b035e63ffec5bacd1f35541e02af5be3f"}
tendermint-light-client = {git = "https://github.com/heliaxdev/tendermint-rs", rev = "ba13c76b035e63ffec5bacd1f35541e02af5be3f"}
tendermint-light-client-verifier = {git = "https://github.com/heliaxdev/tendermint-rs", rev = "ba13c76b035e63ffec5bacd1f35541e02af5be3f"}
tendermint-testgen      = {git = "https://github.com/heliaxdev/tendermint-rs", rev = "ba13c76b035e63ffec5bacd1f35541e02af5be3f"}
